lsi: false
markdown:  redcarpet
permalink: pretty
pygments:  true
timezone: America/Los_Angeles
encoding: UTF-8
exclude: [
  "README.md",
  "bower.json",
  "package.json",
  "LICENSE.md",
  "node_modules",
  "bower_components",
  "vendor",
  "Gruntfile.js",
  "Gemfile*"
]
gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
